export type RawNode = {
  id: number;
  label: string;
  x: number;
  y: number;
  image?: string;
  size?: number;
};
export type RawEdge = {
  from: number;
  to: number;
  color?: string;
  width?: number;
};

export const nodes: RawNode[] = [
  {
    id: 1,
    label: "Hadapsar",
    x: -400,
    y: -100,
    image: "/location-pin.svg",
    size: 30,
  },
  {
    id: 2,
    label: "Manjari Budruk",
    x: -350,
    y: -120,
    image: "/location-pin.svg",
    size: 30,
  },
  {
    id: 3,
    label: "Loni",
    x: -300,
    y: -150,
    image: "/location-pin.svg",
    size: 30,
  },
  {
    id: 4,
    label: "Uruli",
    x: -250,
    y: -170,
    image: "/location-pin.svg",
    size: 30,
  },
  {
    id: 5,
    label: "Yevat",
    x: -200,
    y: -180,
    image: "/location-pin.svg",
    size: 30,
  },
  {
    id: 6,
    label: "Kedgaon",
    x: -150,
    y: -180,
    image: "/location-pin.svg",
    size: 30,
  },
  {
    id: 7,
    label: "Patas",
    x: -100,
    y: -170,
    image: "/location-pin.svg",
    size: 30,
  },
  {
    id: 8,
    label: "Daund Jn",
    x: -50,
    y: -150,
    image: "/location-pin.svg",
    size: 45,
  },
  {
    id: 9,
    label: "Boribiel",
    x: 50,
    y: -120,
    image: "/location-pin.svg",
    size: 30,
  },
  {
    id: 10,
    label: "Malad Gaon",
    x: 100,
    y: -100,
    image: "/location-pin.svg",
    size: 30,
  },
  {
    id: 11,
    label: "Shirsai",
    x: 150,
    y: -70,
    image: "/location-pin.svg",
    size: 30,
  },
  {
    id: 12,
    label: "Katphal",
    x: 200,
    y: -50,
    image: "/location-pin.svg",
    size: 30,
  },
  {
    id: 13,
    label: "Baramati",
    x: 250,
    y: 0,
    image: "/location-pin.svg",
    size: 45,
  },
  {
    id: 14,
    label: "Sangawi",
    x: 200,
    y: 50,
    image: "/location-pin.svg",
    size: 30,
  },
  {
    id: 15,
    label: "Phaltan",
    x: 100,
    y: 100,
    image: "/location-pin.svg",
    size: 30,
  },
  {
    id: 16,
    label: "Surawadi",
    x: 50,
    y: 150,
    image: "/location-pin.svg",
    size: 30,
  },
  {
    id: 17,
    label: "Taradgaon",
    x: 0,
    y: 200,
    image: "/location-pin.svg",
    size: 30,
  },
  {
    id: 18,
    label: "Lonand Jn",
    x: -50,
    y: 250,
    image: "/location-pin.svg",
    size: 45,
  },
  {
    id: 19,
    label: "Nira",
    x: -100,
    y: 200,
    image: "/location-pin.svg",
    size: 30,
  },
  {
    id: 20,
    label: "Valha",
    x: -150,
    y: 150,
    image: "/location-pin.svg",
    size: 30,
  },
  {
    id: 21,
    label: "Daundaj",
    x: -200,
    y: 120,
    image: "/location-pin.svg",
    size: 30,
  },
  {
    id: 22,
    label: "Jejuri",
    x: -250,
    y: 100,
    image: "/location-pin.svg",
    size: 30,
  },
  {
    id: 23,
    label: "Rajevadi",
    x: -300,
    y: 80,
    image: "/location-pin.svg",
    size: 30,
  },
  {
    id: 24,
    label: "Ambale",
    x: -350,
    y: 60,
    image: "/location-pin.svg",
    size: 30,
  },
  {
    id: 25,
    label: "Alandi",
    x: -380,
    y: 40,
    image: "/location-pin.svg",
    size: 30,
  },
  {
    id: 26,
    label: "Sasvad Road",
    x: -400,
    y: 20,
    image: "/location-pin.svg",
    size: 30,
  },
  {
    id: 27,
    label: "Pune Jn",
    x: -450,
    y: -50,
    image: "/location-pin.svg",
    size: 50,
  },
];

export const edges: RawEdge[] = [
  { from: 1, to: 2 },
  { from: 2, to: 3 },
  { from: 3, to: 4 },
  { from: 4, to: 5 },
  { from: 5, to: 6 },
  { from: 6, to: 7 },
  { from: 7, to: 8, color: "red", width: 4 },
  { from: 8, to: 9, color: "red", width: 4 },
  { from: 9, to: 10 },
  { from: 10, to: 11 },
  { from: 11, to: 12 },
  { from: 12, to: 13, color: "green", width: 4 },
  { from: 13, to: 14, color: "green", width: 4 },
  { from: 14, to: 15 },
  { from: 15, to: 16 },
  { from: 16, to: 17 },
  { from: 17, to: 18, color: "orange", width: 4 },
  { from: 18, to: 19 },
  { from: 19, to: 20 },
  { from: 20, to: 21 },
  { from: 21, to: 22 },
  { from: 22, to: 23 },
  { from: 23, to: 24 },
  { from: 24, to: 25 },
  { from: 25, to: 26 },
  { from: 26, to: 27 },
  { from: 27, to: 1 },
];
